<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" 
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform" 
  xmlns:s="http://www.sitemaps.org/schemas/sitemap/0.9"
  exclude-result-prefixes="s">
<xsl:output method="html" encoding="UTF-8" indent="yes"/>

<xsl:template match="/">
  <html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <title>XML Sitemap - ForexNepal</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <style type="text/css">
      body {
        font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
        background-color: #f9f9f9;
        color: #333;
        line-height: 1.6;
      }
      .container {
        max-width: 800px;
        margin: 20px auto;
        background: #fff;
        border: 1px solid #ddd;
        border-radius: 8px;
        padding: 20px 40px;
      }
      h1 {
        font-size: 28px;
        border-bottom: 2px solid #eee;
        padding-bottom: 10px;
        margin-top: 0;
        color: #111;
      }
      table {
        width: 100%;
        border-collapse: collapse;
        margin-top: 20px;
      }
      th, td {
        padding: 12px 15px;
        text-align: left;
        border-bottom: 1px solid #eee;
      }
      th {
        background-color: #fdfdfd;
        font-weight: 600;
        color: #555;
        font-size: 14px;
        text-transform: uppercase;
      }
      tr:hover td {
        background-color: #f0f8ff;
      }
      a {
        text-decoration: none;
        color: #007bff;
        font-weight: 500;
      }
      a:hover {
        text-decoration: underline;
      }
      .meta {
        font-size: 13px;
        color: #555;
      }
    </style>
  </head>
  <body>
    <div class="container">
      <h1>XML Sitemap</h1>
      <p>This XML Sitemap is generated by Grisma for search engines like Google to crawl and index this website.</p>
      
      <!-- This part handles the sitemap *index* (sitemap.xml) -->
      <xsl:if test="count(s:sitemapindex/s:sitemap) > 0">
        <h1>Sitemap Index</h1>
        <table>
          <thead>
            <tr>
              <th>Sitemap URL</th>
              <th>Last Modified</th>
            </tr>
          </thead>
          <tbody>
            <xsl:for-each select="s:sitemapindex/s:sitemap">
              <tr>
                <td>
                  <a href="{s:loc}"><xsl:value-of select="s:loc"/></a>
                </td>
                <td>
                  <xsl:value-of select="concat(
                    substring(s:lastmod, 1, 10),
                    ' ',
                    substring(s:lastmod, 12, 8)
                  )"/>
                </td>
              </tr>
            </xsl:for-each>
          </tbody>
        </table>
      </xsl:if>

      <!-- This part handles the URL *lists* (page-sitemap.xml, post-sitemap.xml, etc.) -->
      <xsl:if test="count(s:urlset/s:url) > 0">
        <h1>URL List</h1>
        <table>
          <thead>
            <tr>
              <th>URL</th>
              <th>Last Modified</th>
              <th>Change Freq.</th>
              <th>Priority</th>
            </tr>
          </thead>
          <tbody>
            <xsl:for-each select="s:urlset/s:url">
              <tr>
                <td>
                  <a href="{s:loc}"><xsl:value-of select="s:loc"/></a>
                </td>
                <td>
                  <xsl:value-of select="concat(
                    substring(s:lastmod, 1, 10),
                    ' ',
                    substring(s:lastmod, 12, 8)
                  )"/>
                </td>
                <td class="meta"><xsl:value-of select="s:changefreq"/></td>
                <td class="meta"><xsl:value-of select="s:priority"/></td>
              </tr>
            </xsl:for-each>
          </tbody>
        </table>
      </xsl:if>
      
    </div>
  </body>
  </html>
</xsl:template>
</xsl:stylesheet>
